
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '#\x97\x08rHd!j\xb8:B\xb3\x0b\xfc~@'
    
_lr_action_items = {'LPARENTHESIS':([31,32,34,],[-28,-29,45,]),'TITLE':([45,],[46,]),'PROJECTNAME':([2,15,],[6,28,]),'ACTIVITY':([48,],[49,]),'DEFAULTPROJECT':([0,],[2,]),'NA':([9,13,16,18,22,29,30,33,35,36,38,40,44,50,],[-20,-23,32,32,-24,32,-19,-22,-25,32,32,-21,-26,-27,]),'EOL':([5,6,10,23,28,49,],[7,8,22,40,43,50,]),'PROJECT':([7,11,12,17,19,20,21,25,26,27,29,35,36,37,41,42,44,50,],[15,15,-8,-11,-16,-7,-9,-10,-13,-6,-12,-25,-17,-14,-4,-15,-26,-27,]),'TASKIDENTIFIER':([9,13,16,18,22,29,30,33,35,36,38,40,44,50,],[-20,-23,31,31,-24,31,-19,-22,-25,31,31,-21,-26,-27,]),'RPARENTHESIS':([46,],[47,]),'TIME':([7,9,10,12,14,16,17,19,24,25,26,29,30,35,36,37,38,39,40,42,43,44,50,],[10,-20,23,10,10,10,-11,39,10,-10,39,-12,-19,-25,-17,39,39,23,-21,39,-5,-26,-27,]),'SEPARATOR':([47,],[48,]),'DAY':([0,],[5,]),'$end':([1,3,4,8,11,12,17,19,20,21,25,26,27,29,35,36,37,41,42,44,50,],[-1,-2,0,-18,-3,-8,-11,-16,-7,-9,-10,-13,-6,-12,-25,-17,-14,-4,-15,-26,-27,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dayinfo':([0,],[1,]),'activitiesdatamult':([7,14,19,24,26,],[12,12,37,12,42,]),'activities':([16,18,38,],[29,36,29,]),'projectsdata':([7,],[11,]),'interval':([7,12,14,16,19,24,26,37,38,42,],[9,9,9,30,9,9,9,9,30,9,]),'defaultproject':([0,],[3,]),'semiinterval':([7,12,14,16,24,],[13,13,13,33,13,]),'changeprojectinfo':([7,11,],[14,24,]),'content':([0,],[4,]),'intervals':([7,12,14,19,24,26,37,42,],[16,16,16,38,16,38,38,38,]),'taskidentifier':([16,18,29,36,38,],[34,34,34,34,34,]),'activitiesdata':([7,12,14,19,24,26,37,42,],[17,25,17,17,17,17,25,25,]),'partialintervals':([7,12,14,24,],[18,18,18,18,]),'partialactivitiesdata':([7,12,14,24,],[19,26,19,19,]),'activity':([16,18,29,36,38,],[35,35,44,44,35,]),'projectdata':([7,14,24,],[20,27,41,]),'partialactivitiesdatamult':([7,14,24,],[21,21,21,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> content","S'",1,None,None,None),
  ('content -> dayinfo','content',1,'p_content','/home/brunore/cs/code/scrum/src/scrumparser.py',139),
  ('content -> defaultproject','content',1,'p_content','/home/brunore/cs/code/scrum/src/scrumparser.py',140),
  ('dayinfo -> DAY EOL projectsdata','dayinfo',3,'p_dayinfo','/home/brunore/cs/code/scrum/src/scrumparser.py',144),
  ('projectsdata -> projectsdata changeprojectinfo projectdata','projectsdata',3,'p_projectsdata_multiple','/home/brunore/cs/code/scrum/src/scrumparser.py',152),
  ('changeprojectinfo -> PROJECT PROJECTNAME EOL','changeprojectinfo',3,'p_changeprojectinfo','/home/brunore/cs/code/scrum/src/scrumparser.py',156),
  ('projectsdata -> changeprojectinfo projectdata','projectsdata',2,'p_projectsdata_single_changeprojectinfo','/home/brunore/cs/code/scrum/src/scrumparser.py',162),
  ('projectsdata -> projectdata','projectsdata',1,'p_projectsdata_single','/home/brunore/cs/code/scrum/src/scrumparser.py',166),
  ('projectdata -> activitiesdatamult','projectdata',1,'p_projectdata_fullintervals','/home/brunore/cs/code/scrum/src/scrumparser.py',170),
  ('projectdata -> partialactivitiesdatamult','projectdata',1,'p_projectdata_partialintervals','/home/brunore/cs/code/scrum/src/scrumparser.py',177),
  ('activitiesdatamult -> activitiesdatamult activitiesdata','activitiesdatamult',2,'p_activitiesdatamult_multiple','/home/brunore/cs/code/scrum/src/scrumparser.py',184),
  ('activitiesdatamult -> activitiesdata','activitiesdatamult',1,'p_activitiesdatamult_single','/home/brunore/cs/code/scrum/src/scrumparser.py',191),
  ('activitiesdata -> intervals activities','activitiesdata',2,'p_activitiesdata','/home/brunore/cs/code/scrum/src/scrumparser.py',195),
  ('partialactivitiesdatamult -> activitiesdatamult partialactivitiesdata','partialactivitiesdatamult',2,'p_partialactivitiesdatamult_multiple1','/home/brunore/cs/code/scrum/src/scrumparser.py',201),
  ('partialactivitiesdatamult -> partialactivitiesdata activitiesdatamult','partialactivitiesdatamult',2,'p_partialactivitiesdatamult_multiple2','/home/brunore/cs/code/scrum/src/scrumparser.py',205),
  ('partialactivitiesdatamult -> activitiesdatamult partialactivitiesdata activitiesdatamult','partialactivitiesdatamult',3,'p_partialactivitiesdatamult_multiple3','/home/brunore/cs/code/scrum/src/scrumparser.py',209),
  ('partialactivitiesdatamult -> partialactivitiesdata','partialactivitiesdatamult',1,'p_partialactivitiesdatamult_single','/home/brunore/cs/code/scrum/src/scrumparser.py',229),
  ('partialactivitiesdata -> partialintervals activities','partialactivitiesdata',2,'p_partialactivitiesdata','/home/brunore/cs/code/scrum/src/scrumparser.py',233),
  ('defaultproject -> DEFAULTPROJECT PROJECTNAME EOL','defaultproject',3,'p_defaultproject','/home/brunore/cs/code/scrum/src/scrumparser.py',239),
  ('intervals -> intervals interval','intervals',2,'p_intervals_multiple','/home/brunore/cs/code/scrum/src/scrumparser.py',243),
  ('intervals -> interval','intervals',1,'p_intervals_single','/home/brunore/cs/code/scrum/src/scrumparser.py',247),
  ('interval -> TIME TIME EOL','interval',3,'p_interval','/home/brunore/cs/code/scrum/src/scrumparser.py',251),
  ('partialintervals -> intervals semiinterval','partialintervals',2,'p_partialintervals_multiple','/home/brunore/cs/code/scrum/src/scrumparser.py',255),
  ('partialintervals -> semiinterval','partialintervals',1,'p_partialintervals_single','/home/brunore/cs/code/scrum/src/scrumparser.py',259),
  ('semiinterval -> TIME EOL','semiinterval',2,'p_semiinterval','/home/brunore/cs/code/scrum/src/scrumparser.py',263),
  ('activities -> activity','activities',1,'p_activities','/home/brunore/cs/code/scrum/src/scrumparser.py',267),
  ('activities -> activities activity','activities',2,'p_activities_multiple','/home/brunore/cs/code/scrum/src/scrumparser.py',271),
  ('activity -> taskidentifier LPARENTHESIS TITLE RPARENTHESIS SEPARATOR ACTIVITY EOL','activity',7,'p_activity_single','/home/brunore/cs/code/scrum/src/scrumparser.py',275),
  ('taskidentifier -> TASKIDENTIFIER','taskidentifier',1,'p_taskidentifier_available','/home/brunore/cs/code/scrum/src/scrumparser.py',285),
  ('taskidentifier -> NA','taskidentifier',1,'p_taskidentifier_notavailable','/home/brunore/cs/code/scrum/src/scrumparser.py',289),
]
