
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xcd\xd8?\x9b\xe0G\xd0j2\xe3\x965\xcf\xacqy'
    
_lr_action_items = {'LPARENTHESIS':([18,21,26,],[-16,27,-15,]),'TITLE':([27,],[30,]),'NUMBER':([19,],[26,]),'PROJECTNAME':([2,15,],[6,24,]),'NUMBERSIGN':([10,11,16,17,20,25,28,34,],[-10,19,19,-9,-12,-13,-11,-14,]),'ACTIVITY':([32,],[33,]),'DEFAULTPROJECT':([0,],[2,]),'NA':([10,11,16,17,20,25,28,34,],[-10,18,18,-9,-12,-13,-11,-14,]),'EOL':([5,6,22,24,33,],[7,8,28,29,34,]),'PROJECT':([9,13,16,20,23,25,34,],[15,-6,-7,-12,-4,-13,-14,]),'SEPARATOR':([31,],[32,]),'RPARENTHESIS':([30,],[31,]),'TIME':([7,10,11,12,14,17,28,29,],[12,-10,12,22,12,-9,-11,-5,]),'DAY':([0,],[5,]),'$end':([1,3,4,8,9,13,16,20,23,25,34,],[-1,-2,0,-8,-3,-6,-7,-12,-4,-13,-14,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dayinfo':([0,],[1,]),'activities':([11,],[16,]),'projectsdata':([7,],[9,]),'interval':([7,11,14,],[10,17,10,]),'defaultproject':([0,],[3,]),'changeprojectinfo':([9,],[14,]),'content':([0,],[4,]),'intervals':([7,14,],[11,11,]),'taskidentifier':([11,16,],[21,21,]),'activity':([11,16,],[20,25,]),'projectdata':([7,14,],[13,23,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> content","S'",1,None,None,None),
  ('content -> dayinfo','content',1,'p_content','/home/brunore/cs/workspace/utils/src/scrum2.py',123),
  ('content -> defaultproject','content',1,'p_content','/home/brunore/cs/workspace/utils/src/scrum2.py',124),
  ('dayinfo -> DAY EOL projectsdata','dayinfo',3,'p_dayinfo','/home/brunore/cs/workspace/utils/src/scrum2.py',128),
  ('projectsdata -> projectsdata changeprojectinfo projectdata','projectsdata',3,'p_projectsdata_multiple','/home/brunore/cs/workspace/utils/src/scrum2.py',136),
  ('changeprojectinfo -> PROJECT PROJECTNAME EOL','changeprojectinfo',3,'p_changeprojectinfo','/home/brunore/cs/workspace/utils/src/scrum2.py',140),
  ('projectsdata -> projectdata','projectsdata',1,'p_projectsdata_single','/home/brunore/cs/workspace/utils/src/scrum2.py',143),
  ('projectdata -> intervals activities','projectdata',2,'p_projectdata','/home/brunore/cs/workspace/utils/src/scrum2.py',147),
  ('defaultproject -> DEFAULTPROJECT PROJECTNAME EOL','defaultproject',3,'p_defaultproject','/home/brunore/cs/workspace/utils/src/scrum2.py',152),
  ('intervals -> intervals interval','intervals',2,'p_intervals_multiple','/home/brunore/cs/workspace/utils/src/scrum2.py',156),
  ('intervals -> interval','intervals',1,'p_intervals_single','/home/brunore/cs/workspace/utils/src/scrum2.py',160),
  ('interval -> TIME TIME EOL','interval',3,'p_interval','/home/brunore/cs/workspace/utils/src/scrum2.py',164),
  ('activities -> activity','activities',1,'p_activities','/home/brunore/cs/workspace/utils/src/scrum2.py',168),
  ('activities -> activities activity','activities',2,'p_activities_multiple','/home/brunore/cs/workspace/utils/src/scrum2.py',172),
  ('activity -> taskidentifier LPARENTHESIS TITLE RPARENTHESIS SEPARATOR ACTIVITY EOL','activity',7,'p_activity_single','/home/brunore/cs/workspace/utils/src/scrum2.py',176),
  ('taskidentifier -> NUMBERSIGN NUMBER','taskidentifier',2,'p_taskidentifier_available','/home/brunore/cs/workspace/utils/src/scrum2.py',184),
  ('taskidentifier -> NA','taskidentifier',1,'p_taskidentifier_notavailable','/home/brunore/cs/workspace/utils/src/scrum2.py',188),
]
