
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x14!\xa9\x0c{@p\xf8A\xda\x10h\x7f\x84R\x9d'
    
_lr_action_items = {'LPARENTHESIS':([22,25,32,],[-20,33,-19,]),'TITLE':([33,],[35,]),'NUMBER':([23,],[32,]),'PROJECTNAME':([2,19,],[6,30,]),'NUMBERSIGN':([11,12,13,14,16,20,21,24,26,27,28,31,39,],[-11,-14,23,23,-15,23,-10,-13,-16,23,-12,-17,-18,]),'ACTIVITY':([37,],[38,]),'DEFAULTPROJECT':([0,],[2,]),'NA':([11,12,13,14,16,20,21,24,26,27,28,31,39,],[-11,-14,22,22,-15,22,-10,-13,-16,22,-12,-17,-18,]),'EOL':([5,6,9,17,30,38,],[7,8,16,28,34,39,]),'PROJECT':([10,15,20,26,27,29,31,39,],[19,-6,-7,-16,-8,-4,-17,-18,]),'SEPARATOR':([36,],[37,]),'RPARENTHESIS':([35,],[36,]),'TIME':([7,9,11,13,18,21,28,34,],[9,17,-11,9,9,-10,-12,-5,]),'DAY':([0,],[5,]),'$end':([1,3,4,8,10,15,20,26,27,29,31,39,],[-1,-2,0,-9,-3,-6,-7,-16,-8,-4,-17,-18,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dayinfo':([0,],[1,]),'activities':([13,14,],[20,27,]),'projectsdata':([7,],[10,]),'interval':([7,13,18,],[11,21,11,]),'defaultproject':([0,],[3,]),'semiinterval':([7,13,18,],[12,24,12,]),'changeprojectinfo':([10,],[18,]),'content':([0,],[4,]),'intervals':([7,18,],[13,13,]),'taskidentifier':([13,14,20,27,],[25,25,25,25,]),'partialintervals':([7,18,],[14,14,]),'activity':([13,14,20,27,],[26,26,31,31,]),'projectdata':([7,18,],[15,29,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> content","S'",1,None,None,None),
  ('content -> dayinfo','content',1,'p_content','/home/brunore/cs/workspace/utils/src/scrum2.py',125),
  ('content -> defaultproject','content',1,'p_content','/home/brunore/cs/workspace/utils/src/scrum2.py',126),
  ('dayinfo -> DAY EOL projectsdata','dayinfo',3,'p_dayinfo','/home/brunore/cs/workspace/utils/src/scrum2.py',130),
  ('projectsdata -> projectsdata changeprojectinfo projectdata','projectsdata',3,'p_projectsdata_multiple','/home/brunore/cs/workspace/utils/src/scrum2.py',138),
  ('changeprojectinfo -> PROJECT PROJECTNAME EOL','changeprojectinfo',3,'p_changeprojectinfo','/home/brunore/cs/workspace/utils/src/scrum2.py',142),
  ('projectsdata -> projectdata','projectsdata',1,'p_projectsdata_single','/home/brunore/cs/workspace/utils/src/scrum2.py',146),
  ('projectdata -> intervals activities','projectdata',2,'p_projectdata_fullintervals','/home/brunore/cs/workspace/utils/src/scrum2.py',150),
  ('projectdata -> partialintervals activities','projectdata',2,'p_projectdata_partialintervals','/home/brunore/cs/workspace/utils/src/scrum2.py',155),
  ('defaultproject -> DEFAULTPROJECT PROJECTNAME EOL','defaultproject',3,'p_defaultproject','/home/brunore/cs/workspace/utils/src/scrum2.py',160),
  ('intervals -> intervals interval','intervals',2,'p_intervals_multiple','/home/brunore/cs/workspace/utils/src/scrum2.py',164),
  ('intervals -> interval','intervals',1,'p_intervals_single','/home/brunore/cs/workspace/utils/src/scrum2.py',168),
  ('interval -> TIME TIME EOL','interval',3,'p_interval','/home/brunore/cs/workspace/utils/src/scrum2.py',172),
  ('partialintervals -> intervals semiinterval','partialintervals',2,'p_partialintervals_multiple','/home/brunore/cs/workspace/utils/src/scrum2.py',176),
  ('partialintervals -> semiinterval','partialintervals',1,'p_partialintervals_single','/home/brunore/cs/workspace/utils/src/scrum2.py',180),
  ('semiinterval -> TIME EOL','semiinterval',2,'p_semiinterval','/home/brunore/cs/workspace/utils/src/scrum2.py',184),
  ('activities -> activity','activities',1,'p_activities','/home/brunore/cs/workspace/utils/src/scrum2.py',188),
  ('activities -> activities activity','activities',2,'p_activities_multiple','/home/brunore/cs/workspace/utils/src/scrum2.py',192),
  ('activity -> taskidentifier LPARENTHESIS TITLE RPARENTHESIS SEPARATOR ACTIVITY EOL','activity',7,'p_activity_single','/home/brunore/cs/workspace/utils/src/scrum2.py',196),
  ('taskidentifier -> NUMBERSIGN NUMBER','taskidentifier',2,'p_taskidentifier_available','/home/brunore/cs/workspace/utils/src/scrum2.py',204),
  ('taskidentifier -> NA','taskidentifier',1,'p_taskidentifier_notavailable','/home/brunore/cs/workspace/utils/src/scrum2.py',208),
]
