MAIN_SPREADSHEET_KEY = '0AvzpGlSBqZIndHduSjJZTHg0cXZkRERYUWZyYkpzWHc'
SOULMATES_SPREADSHEET_KEY = '0AvzpGlSBqZIndHlGcTZJU0ZBeWU2emI0V3A4cUlXWkE'
GOOGLE_DRIVE_USER = None
GOOGLE_DRIVE_PWD = None

try:
    from local_settings import *
except:
    pass